### ISSUE TITLE
Ckeditor Import Issue

### ISSUE THREAD

**Issue by BackdevHong** [pet-platform/pet-platform-front#2]
<img width="626" alt="image" src="https://github.com/pet-platform/pet-platform-front/assets/97325091/56ec194a-2c10-4e36-9ced-71e903dc7113">

Ckeditor 패키지 설치했음에도 불구하고, import가 안되는 버그 발생.

**Comment by BackdevHong** [comment]
@PeterJSung 혹시 이거 CKEditor Custom Builder 이용해서 했어야 했을까요??

**Comment by PeterJSung** [comment]
@BackdevHong 아뇨 이거커스텀빌드아니고요 그냥 node modules 에 설치한거에요. app router 에서 커스텀빌드 안됩니다.

**Comment by BackdevHong** [comment]
> @BackdevHong 아뇨 이거커스텀빌드아니고요 그냥 node modules 에 설치한거에요. app router 에서 커스텀빌드 안됩니다.

스읍.. 왜이럴까요 일단 저도 node modules에 설치하긴 했는데

**Comment by BackdevHong** [comment]
해결했습니다!
@ckeditor/ckeditor5-react
@ckeditor/ckeditor5-build-classic

이거 두개를 따로 깔았어야 됬던거군요!
